version: '3.8'

services:
  django:
    build:
      context: ./Iskowela
    ports:
      - '8000:8000'
    depends_on:
      - rasa
      - action_server

  rasa:
    container_name: "rasa_server"
    build: 
      context:  ./rasa_chatbot
    ports: 
      - "5005:5005"
    depends_on:
      - action_server
        
  action_server:
    container_name: "action_server"
    build: 
      context: ./rasa_chatbot/actions
    ports:
      - 5055:5055