# Generated by Django 4.1.7 on 2023-03-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='school_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
