# Generated by Django 4.1.7 on 2023-03-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_school_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
