# Generated by Django 4.1.7 on 2023-03-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_toggles_school_name_post_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='school_name',
        ),
    ]
