# Generated by Django 4.1.7 on 2023-02-26 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, unique=True)),
                ('stype', models.IntegerField(choices=[(1, 'Physical'), (2, 'Online')])),
                ('name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, unique=True)),
                ('stype', models.IntegerField(choices=[(1, 'Offline'), (2, 'Online')])),
                ('name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('cud', models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')])),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Place_Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, unique=True)),
                ('stype', models.IntegerField(choices=[(1, 'Health'), (2, 'Food'), (3, 'Finance'), (4, 'Store'), (5, 'Etc')])),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Place_Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, unique=True)),
                ('stype', models.IntegerField(choices=[(1, 'Health'), (2, 'Food'), (3, 'Finance'), (4, 'Store'), (5, 'Etc')])),
                ('name', models.CharField(max_length=100)),
                ('cud', models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')])),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
