# Generated by Django 4.1.7 on 2023-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_markers',
            name='stype',
            field=models.IntegerField(choices=[(1, 'Offline'), (2, 'Online')]),
        ),
    ]
