# Generated by Django 4.1.7 on 2023-02-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_alter_event_markers_stype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_markers',
            old_name='stype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='event_suggestions',
            old_name='stype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='place_markers',
            old_name='stype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='place_suggestions',
            old_name='stype',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='event_markers',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='event_suggestions',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='place_markers',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='place_suggestions',
            name='desc',
        ),
        migrations.AddField(
            model_name='event_markers',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event_suggestions',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place_markers',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place_suggestions',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event_markers',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event_suggestions',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='place_markers',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='place_suggestions',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
