# Generated by Django 4.1.7 on 2023-03-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_event_markers_profile_event_suggestions_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_suggestions',
            name='place_marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='markers.place_markers'),
        ),
    ]
