# Generated by Django 4.1.7 on 2023-03-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0007_place_suggestions_place_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_suggestions',
            name='event_marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='markers.event_markers'),
        ),
    ]
