# Generated by Django 3.0.4 on 2020-04-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('interactive_map_comment', models.TextField(default='')),
                ('interactive_map_rating', models.IntegerField(default=0)),
                ('chatbot_comment', models.TextField(default='')),
                ('chatbot_rating', models.IntegerField(default=0)),
                ('overall_comment', models.TextField(default='')),
                ('overall_rating', models.IntegerField(default=0)),
            ],
        ),
    ]
