# Generated by Django 3.0.4 on 2020-04-10 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ssr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssr',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
