# Generated by Django 3.0.3 on 2020-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr', '0002_ssr_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssr',
            name='chatbot_rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AlterField(
            model_name='ssr',
            name='interactive_map_rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AlterField(
            model_name='ssr',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
    ]
