# Generated by Django 4.1.7 on 2023-03-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_banner'),
        ('ssr', '0003_auto_20200413_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssr',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
