# Generated by Django 4.2.1 on 2023-05-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_latitude_profile_longitude'),
        ('ssr', '0005_alter_ssr_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssr',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
