# Generated by Django 4.2.1 on 2023-05-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr', '0006_alter_ssr_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssr',
            old_name='interactive_map_comment',
            new_name='information_modules_comment',
        ),
        migrations.RenameField(
            model_name='ssr',
            old_name='interactive_map_rating',
            new_name='information_modules_rating',
        ),
        migrations.AddField(
            model_name='ssr',
            name='markers_module_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ssr',
            name='markers_module_rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
    ]
