# Generated by Django 3.0.4 on 2020-04-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='place_markers_dataset_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='etc_markers_dataset_link',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='finance_markers_dataset_link',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='food_markers_dataset_link',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_markers_dataset_link',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='newgame_markers_dataset_link',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='newgame_textfield',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_markers_dataset_link',
            field=models.CharField(default='', max_length=80),
        ),
    ]
