# Generated by Django 4.1.5 on 2023-01-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_new_game_dataset_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field= models.ImageField(null= True, blank=True, upload_to='media'),
        ),
    ]
