# Generated by Django 4.1.5 on 2023-01-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230105_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='banner.jpg', upload_to='media'),
        ),
    ]
