# Generated by Django 4.1.7 on 2023-02-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='banner.jpg', upload_to='media'),
        ),
    ]
