# Generated by Django 4.1.7 on 2023-03-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_etc_markers_dataset_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
    ]
