# Generated by Django 4.1.7 on 2023-03-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotmonitor',
            name='datetime',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homemonitor',
            name='datetime',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='datetime',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='markermonitor',
            name='datetime',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
