# Generated by Django 4.1.7 on 2023-03-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemonitor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='infomonitor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='markermonitor',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ChatbotMonitor',
        ),
        migrations.DeleteModel(
            name='HomeMonitor',
        ),
        migrations.DeleteModel(
            name='InfoMonitor',
        ),
        migrations.DeleteModel(
            name='MarkerMonitor',
        ),
    ]
