# Generated by Django 4.1.7 on 2023-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_timetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
