# Generated by Django 4.1.7 on 2023-03-26 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_monitor_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 16, 38, 22, 744808, tzinfo=datetime.timezone.utc)),
        ),
    ]
