# Generated by Django 4.2.1 on 2023-05-18 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_timetracking_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 10, 25, 892793, tzinfo=datetime.timezone.utc)),
        ),
    ]
