# Generated by Django 4.2.1 on 2023-05-17 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_timetracking_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 13, 37, 43, 639255, tzinfo=datetime.timezone.utc)),
        ),
    ]
