# Generated by Django 4.2.1 on 2023-05-18 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_alter_timetracking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 21, 39, 19, 633681, tzinfo=datetime.timezone.utc)),
        ),
    ]
