# Generated by Django 4.2.1 on 2023-05-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_alter_timetracking_last_update'),
        ('analytics', '0014_alter_timetracking_start_time'),
    ]

    operations = [
    ]
