# Generated by Django 4.2.1 on 2023-05-26 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_merge_20230522_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='last_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 26, 15, 10, 9, 712538, tzinfo=datetime.timezone.utc)),
        ),
    ]
