# Generated by Django 4.1.4 on 2022-12-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processguide',
            old_name='process',
            new_name='process_name',
        ),
    ]
