# Generated by Django 4.1.4 on 2022-12-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_processguide_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarships',
            old_name='scholarship',
            new_name='scholarship_name',
        ),
    ]
