# Generated by Django 4.1.7 on 2023-02-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_alter_courses_course_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_list',
            field=models.JSONField(default={}),
        ),
    ]
