# Generated by Django 4.2.1 on 2023-05-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_remove_courses_schoolid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processguide',
            name='apply',
            field=models.IntegerField(choices=[(1, 'Others'), (2, 'Apply')], default=1),
        ),
    ]
